import 'package:get/get.dart';

class AppTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'Account': 'الحساب',
          'My Account': 'إعدادات الحساب',
          'Set Shopping delivery address': 'تعيين عنوان التسليم للتسوق',
          'My Cart': 'سلة التسوق',
          'In-progress and Compleate Order': 'الطلبات قيد التنفيذ والمكتملة',
          'Notification': 'رسالة الإشعار',
          'Notification Message': 'رسالة الإخطار',
          'Add and Remove Products and move to checkout':
              'إضافة وإزالة المنتجات والانتقال إلى الخروج',
          'LogOUt': 'تسجيل الخروج',
          'LogOut Your Application': 'تسجيل الخروج من التطبيق',
          'App Setting': 'إعدادات التطبيق',
          'Maps Tracking': 'تتبع الخرائط',
          'Translate': 'ترجمة',
          'Traking Product': 'تتبع المنتج',
          'Translate Your App': 'ترجمة التطبيق الخاص بك',
          'Account Setting': 'إعدادات الحساب',
          'Category': 'فئة',
          'Favorite': 'المفضلة',
          'Please, Add your favorite proudcts': 'من فضلك، أضف فخرك المفضل',
          'Search in The Store': 'ابحث في المتجر',
          'Welcome': 'اهلا بك',
          'Hello! Welcome to the app!': 'مرحبًا! مرحبا بكم في التطبيق!',
          "We're happy to have you here!": 'نحن سعداء بوجودك هنا!',
          'Enjoy your time with us!': 'استمتع وقتك معنا!',
          'Popular Products': 'المنتجات الشعبية',
          'God Day For Shopping': 'يوم جميل للتسوق',
          'Skip': 'تخطي ',
          'Shop From your favorite stores': 'تسوق من المتاجر المفضلة لديك',
          'Discover a world of convenience and endless choices. Get ready to experience the best of online shopping right at your fingertips.':
              'اكتشف عالمًا من الراحة والخيارات التي لا نهاية لها. استعد لتجربة أفضل ما في التسوق عبر الإنترنت في متناول يدك.',
          'Get IT Delivered': 'احصل على تسليم تكنولوجيا المعلومات',
          'Enjoy fast and reliable delivery straight to your doorstep. Sit back and relax while we bring your purchases to you.':
              'استمتع بالتسليم السريع والموثوق مباشرة إلى باب منزلك. اجلس واسترخي بينما نحضر مشترياتك إليك.',
          'Flexible payment':
              'اختر من بين مجموعة متنوعة من خيارات الدفع التي تناسب احتياجاتك. نحن نجعل التسوق سهلاً ومريحًا بالنسبة لك.',
          'Please enter a valid email': 'Please enter a valid email',
          'E-mail': 'بريد إلكتروني',
          'Password': 'كلمة المرور',
          'Please enter a valid password': 'الرجاء إدخال كلمة السر الصحيحة',
          'Sign In': 'تسجيل الدخول',
          'Create Account': 'إنشاء حساب',
          'Welcome back,': '"مرحبًا بعودتك،',
          'Discover limited choices and unmatched\nconvenience.':
              'اكتشف خيارات محدودة وراحة\nلا مثيل لها.',
          'Or Sign With': 'أو قم بالتوقيع مع',
          'Remember Me': 'ذكرني',
          'Forgot Password ?': 'هل نسيت كلمة السر ؟',
          'Letes Create Your Account': 'يتيح لك إنشاء حسابك',
          'First Name': 'الاسم الأول',
          'Last Name': 'اسم العائلة',
          'Please enter a valid User Last Name': 'الرجاء إدخال اسم عائلة مستخدم صالح',
          'Please enter a valid User User Name': 'الرجاء إدخال اسم مستخدم صالح',
          'User Name': 'اسم المستخدم',
          'Please enter a valid E-mail': 'يرجى إدخال البريد الإلكتروني الصحيح',
          'Please enter a valid Phone Number': 'يرجى إدخال رقم هاتف صالح',
          'Phone Number': 'رقم التليفون',
          'Please enter a valid Password': 'الرجاء إدخال كلمة السر الصحيحة',
          'isAgreeTo': 'انت موافق',
          'privacePolicy': 'سياسة الخصوصية',
          'ternsOfUse': 'ternsOfUse',
          'and': 'و',
          'Verify your email address!': 'التحقق من عنوان بريدك الإلكتروني!',
          'congratulations Your Account Aeaites: Verify Your Email to Start Shopping and Experience a world of Univaled  Deals and Personalized Offers': 'تهانينا على حسابك Aeaites: قم بالتحقق من بريدك الإلكتروني لبدء التسوق وتجربة عالم من الصفقات التي لا مثيل لها والعروض المخصصة',
          'Continue': 'يكمل',
          'Resed Email': 'ارسال ايميل اخر',
          'ForgetPassword': 'نسيت كلمة المرور',
          'Dont worry somthing peopele can forget too. enter your email and we will send you a password reser link.': 'لا تقلق، هناك شيء يمكن أن ينساه الناس أيضًا. أدخل بريدك الإلكتروني وسنرسل لك رابط حفظ كلمة المرور.',
          'Reset Password': 'إعادة تعيين كلمة المرور',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
          'Account': 'Account',
        },
        'en': {
          'Account': 'Account',
          'Account Setting': 'Account Setting',
          'Set Shopping delivery address': 'Set Shopping delivery address',
          'My Cart': 'My Cart',
          'In-progress and Compleate Order': 'In-progress and Compleate Order',
          'Notification': 'Notification Message',
          'LogOUt': 'LogOUt',
          'LogOut Your Application': 'LogOut Your Application',
          'App Setting': 'App Setting',
          'Maps Tracking': 'Maps Tracking',
          'Translate': 'Translate',
          'Translate Your App': 'Translate Your App',
        },
        'fr': {
          'Account': 'Compte',
          'My Account': 'Paramètres du compte',
          'Set Shopping delivery address':
              'Définir l\'adresse de livraison des achats',
          'My Cart': 'Mon panier',
          'In-progress and Compleate Order': 'Commandes en cours et complètes',
          'Notification': 'Message de notification',
          'LogOUt': 'Se déconnecter',
          'LogOut Your Application': 'Déconnectez votre application',
          'App Setting': 'Paramètres de l\'application',
          'Maps Tracking': 'Suivi des cartes',
          'Translate': 'Traduire',
          'Translate Your App': 'Traduire votre application',
        },
      };
}
